- name: nginx install and run
  hosts: frontend
  become: yes # sudo access
  tasks:
  - name: install nginx server
    ansible.builtin.package:
      name: nginx
      state: present
  
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
# - name: Install nginx
#   hosts: frontend
#   become: yes
#   tasks:
#     - name: Install nginx
#       ansible.builtin.package:
#         name: nginx
#         state: present

#     - name: Start nginx
#       ansible.builtin.service:
#         name: nginx
#         state: started
#         enabled: yes 